### ISSUE TITLE
iOS Application Displays "Getting GPS Location" then Crashes 

### ISSUE THREAD

**Issue by asikand-view** [navisens/iOS-Plugin#1]
I followed the video tutorial, added the permissions in Info.plist, disabled bitcode, etc. 

Error is CFArrayGetValueAtIndex

![screen shot 2017-08-02 at 12 17 19 pm](https://user-images.githubusercontent.com/29871578/28890810-34fd50d6-777d-11e7-969d-0c62a1da93dc.png)
![screen shot 2017-08-02 at 12 21 43 pm](https://user-images.githubusercontent.com/29871578/28890812-36e0a0ba-777d-11e7-9836-064fb527c778.png)

**Comment by lucasnavisens** [comment]
Hi,

1/ can you confirm the location permissions of your application and make sure you have authorized CLLocationManager to acquire data?

2/ Can you try our latest plugins ? It's been a year this problem may have been fixed.

Let me know how it goes.
Cheers.
