### ISSUE TITLE
Plugins need to be compiled for SWIFT5  (NavisensPlugins/NavisensCore)

### ISSUE THREAD

**Issue by csmobile** [navisens/iOS-Plugin#2]
When adding NavisensCore to a project in Xcode(version 10.2.1, running on macOS Mohave version 10.14.4) Xcode complains about the NavisensCore plugin and shows the error message "Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler".  This happens even if the project language version is set to Swift 4.2.

**Comment by SergioNG-GL** [comment]
Hi, I'm trying to use the plugins as well, in this case with Xcode Version 11.0 (11A420a) and I'm getting a similar error, any ideas on how can we bypass this or any updates on what is planned to address this?

Error on line 'import NavisensCore':
"Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler: /Users/sergio.nunez/SE/PJ/ios/IOSNavisensTest/Pods/NavisensPlugins/navisenscore/NavisensCore.framework/Modules/NavisensCore.swiftmodule/x86_64.swiftmodule"

**Comment by jamesgrantham** [comment]
Hi Sergio,
We will be issuing an update to this next week. Thanks!

**Comment by jamesgrantham** [comment]
Hi Sergio,
The plugins should be updated now. Please let me know if you have any other issues.
