### ISSUE TITLE
Can provide the OC version of the library?

### ISSUE THREAD

**Issue by lixiayi** [navisens/iOS-Plugin#3]
I am not found the OC version of plugin, in my project I want to use the NaviBeacon in Object-C.
please help.

**Comment by jamesgrantham** [comment]
Hi there, thank you for your interest in our SDK. Currently there are no plans to add objective-c support for these plugins. My suggestion would be that you either transition to swift with your project or create swift wrapper object to act as bridge between our plugins and your other code.

**Comment by lixiayi** [comment]
thank you for your relpy.
